// packages/vue/src/Skeleton.vue
<script setup lang="ts">
import { cn } from "@viliha/vui-core";
import { computed } from "vue";

const props = defineProps<{ class?: string }>();
const classes = computed(() => cn("animate-pulse rounded-md bg-accent", props.class));
</script>

<template>
  <div data-slot="skeleton" :class="classes" />
</template>

// packages/ui/src/skeleton.tsx
import * as React from "react";

import { cn } from "./utils";

function Skeleton({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="skeleton"
      className={cn("animate-pulse rounded-md bg-accent", className)}
      {...props}
    />
  );
}

export { Skeleton };
