// packages/ui/src/switch.tsx
"use client";

import * as React from "react";
import { Switch as SwitchPrimitive } from "radix-ui";

import { SWITCH_ROOT, SWITCH_THUMB } from "./class-variants";
import { cn } from "./utils";

function Switch({
  className,
  size = "default",
  ...props
}: React.ComponentProps<typeof SwitchPrimitive.Root> & {
  size?: "sm" | "default";
}) {
  return (
    <SwitchPrimitive.Root
      data-slot="switch"
      data-size={size}
      className={cn(SWITCH_ROOT, className)}
      {...props}
    >
      <SwitchPrimitive.Thumb
        data-slot="switch-thumb"
        className={cn(SWITCH_THUMB)}
      />
    </SwitchPrimitive.Root>
  );
}

export { Switch };

// packages/vue/src/Switch.vue
<script setup lang="ts">
import { SWITCH_ROOT, SWITCH_THUMB, cn } from "@viliha/vui-core";
import { SwitchRoot, SwitchThumb } from "reka-ui";
import { computed } from "vue";

const model = defineModel<boolean>();
const props = withDefaults(
  defineProps<{ size?: "sm" | "default"; disabled?: boolean; class?: string }>(),
  { size: "default" },
);

const classes = computed(() => cn(SWITCH_ROOT, props.class));
</script>

<template>
  <SwitchRoot
    v-model="model"
    data-slot="switch"
    :data-size="size"
    :disabled="disabled"
    :class="classes"
  >
    <SwitchThumb data-slot="switch-thumb" :class="SWITCH_THUMB" />
  </SwitchRoot>
</template>
